### ISSUE TITLE
KeyError: 'length'

### ISSUE THREAD

**Issue by ocstx** [ArturKlauser/pymol-pdb-plugin#9]
Hello
I installed the plugin following the instructions. (all when OK)
but I obtain this error when I'm trying to use it. (see below)

I'm using pymol 2.3.0 installed with homebrew in a High Sierra OSX
I have used pdb 2qgu to test it.
I have tested both "Domains" and "all" with the same error:

Traceback (most recent call last):
  File "/usr/local/Cellar/pymol/2.3.0/libexec/lib/python3.8/site-packages/pmg_tk/startup/PDB_plugin.py", line 1430, in <lambda>
    addmenuitemqt(submenu + 'Domains', lambda: gui.analyze_domains())
  File "/usr/local/Cellar/pymol/2.3.0/libexec/lib/python3.8/site-packages/pmg_tk/startup/PDB_plugin.py", line 1174, in analyze_domains
    PDBe_startup(pdbid, 'domains')
  File "/usr/local/Cellar/pymol/2.3.0/libexec/lib/python3.8/site-packages/pmg_tk/startup/PDB_plugin.py", line 1111, in PDBe_startup
    molecules.show()
  File "/usr/local/Cellar/pymol/2.3.0/libexec/lib/python3.8/site-packages/pmg_tk/startup/PDB_plugin.py", line 885, in show
    display_type, selections = self._process_molecule(molecule)
  File "/usr/local/Cellar/pymol/2.3.0/libexec/lib/python3.8/site-packages/pmg_tk/startup/PDB_plugin.py", line 847, in _process_molecule
    length = molecule['length']
KeyError: 'length'

**Comment by L-G-g** [comment]
Same error here with 1OSF
